openapi: 3.0.0
info:
  version: 1.0.0
  title: Teko Api Specification
  contact:
    email: tien.dv@teko.vn
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://teko-vn.github.io/api-docs/Teko-Logo-01.svg"
  description: >
    This documentation describes APIs used in/exposed from Teko micro-services ecosystem

    # Introduction

    These specifications are following

    [OpenAPI 3.0.0
    format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md).

tags:
  - name: Vouchers
    description: Provides apis for voucher service
  - name: IAM API
    description: |
      We provide four examples one for each of the grant types defined by the [OAuth2 RFC 6749](https://tools.ietf.org/html/rfc6749).
      These grant types (or workflows) are:
      1. Authorization Code Grant (Web Application Flow).
      2. The Implicit Grant (or Mobile / Single Page Application Flow).
      3. The Resource Owner Password Credentials Grant  (or, more succinctly, the Legacy Application Flow).
      4. The Client Credentials Grant (or Backend Application Flow).

      For OAuth2, you can see example to connect with OAuth2 [here](https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html).

      In addition, we also support [OpenID Connect Flow](https://openid.net/connect/) which has been developed by extending OAuth 2.0.

      OAuth 2.0 is a specification as to how to issue `access tokens`. It is defined in RFC 6749 (The OAuth 2.0 Authorization Framework).

      OpenID Connect is a specification as to how to issue ID tokens. The main part is defined in OpenID Connect Core 1.0.
  - name: External Promotion
    description: Provide apis for other services to get promotion info

servers:
  - url: "http://example.com/api/v1"
  - url: "https://example.com/api/v1"
x-tagGroups:
  - name: Offline Sales
    tags:
      - Vouchers
  - name: Identity Platform
    tags:
      - IAM API
  - name: Price And Promotions
    tags:
      - Price & Promotion API
